channels:
  - defaults
dependencies:
  - jupyterlab
  - jupyter
  - pandas
  - python=3.8
  - scikit-learn=0.24
  - numpy
  - seaborn
  - matplotlib
  - statsmodels
  - tabulate
  - pyarrow
  - fastparquet
  - nltk
  - imbalanced-learn
  - streamlit
